resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/drnic/flight-school
    branch: master

- name: staging-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: drnic@starkandwayne.com
    password: ((cf-password))
    organization: starkandwayne
    space: flight-school

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
  - put: staging-app
    params:
      manifest: flight-school/manifest.yml

